### ISSUE TITLE
Wrong path to index.html when running in debug

### ISSUE THREAD

**Issue by smithmx** [dolittle-interaction/AspNetCore#3]

**Comment by smithmx** [comment]
System.IO.FileNotFoundException: Could not find file '/Users/michael/.vscode/extensions/ms-vscode.csharp-1.14.0/.debugger/wwwroot/index.html'.
File name: '/Users/michael/.vscode/extensions/ms-vscode.csharp-1.14.0/.debugger/wwwroot/index.html'
   at System.IO.FileInfo.get_Length()
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.<SendFileAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by smithmx** [comment]
Works ok when you attach the debugger, so not a priority
