### ISSUE TITLE
Ambiguous Commands by name causes problems, even though they are in different namespaces

### ISSUE THREAD

**Issue by einari** [dolittle-interaction/AspNetCore#5]
There is a problem handling CommandRequests from frontend through a CommandCoordinator when we have multiple Commands with the same name.

I think that it's related to this issue, @einari

If you can group Commands per namespace in a dictionary that would help solve the problem? A CommandRequest already has a CorrelationId and a Type in place, should use that in lookup(?)

Could be related to frontend things - look at [CBS](https://github.com/IFRCGo/cbs)

**Comment by woksin** [comment]
A little more context when handling a Command from frontend:

CommandRequest results in a CommandResult where success = false because it comes accross this exception:

message: "Sequence contains more than one element"

stackTrace; "   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Dolittle.Applications.ApplicationStructureMap.GetBestMatchingTypeFor(IEnumerable`1 types)
   at Dolittle.Applications.ApplicationArtifactResolver.Resolve(IApplicationArtifactIdentifier identifier)
   at Dolittle.Commands.Handling.CommandRequestToCommandConverter.Convert(CommandRequest request)
   at Dolittle.Commands.Validation.CommandValidator.Validate(CommandRequest command)
   at Dolittle.Runtime.Commands.Validation.CommandValidators.Validate(CommandRequest command)
   at Dolittle.Runtime.Commands.Coordination.CommandCoordinator.Handle(ITransaction transaction, CommandRequest command)"

**Comment by einari** [comment]
This is somewhat related to [this issue](https://github.com/dolittle/DotNET.SDK/issues/21). My theory is that once we clear up all dangling things related to `ApplicationArtifactIdentifier`we will be in a good place with this as problem as well. Should use this as a test case if it is related.

**Comment by woksin** [comment]
This problem should go away when we're landing on the new solution for Artifacts
